version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
      - image: cmake:latest

    steps:
      - checkout
      - run: mkdir build && cd build
      - run: cmake ..
      - run: make -j8
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest